version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: usedcar
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ps
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: always
networks:
  backend:

